### ISSUE TITLE
Very low .webm video quality 

### ISSUE THREAD

**Issue by ryanbugg** [plugorgau/bbb-render#23]
Any ideas how to improve video output quality for .webm both the slides and the speaker videos are pretty low quality.

**Comment by jhenstridge** [comment]
The bbb-render scripts just assemble whatever recording output your BBB install creates.

You might have some luck editing the [`presentation.yml` file](https://github.com/bigbluebutton/bigbluebutton/blob/main/record-and-playback/presentation/scripts/presentation.yml). There are configuration settings to change the resolution and framerate of the different webm fiiles. Looking [at the documentation](https://docs.bigbluebutton.org/admin/configuration-files.html#local-overrides-for-configuration-settings), it seems like you can provide your own copy in `/etc/bigbluebutton/recording/presentation.yml`.

Other than that, make sure you use "High" or "High definition" when connecting the webcam to the meeting.
